pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.minecraftforge.gradle') useModule('net.minecraftforge.gradle:ForgeGradle:6.0.54')
        }
    }
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}
rootProject.name = 'genesis-core'
